language: csharp
solution: GeekTools.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore GeekTools.sln
after_script:
  - nunit-console GeekToolsTest/bin/Release/GeekToolsTest.dll
sudo: false
