language: csharp
solution: ./src/GeekTools.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./src/GeekTools.sln

script:
  - xbuild ./src/GeekTools.sln
  - nunit-console ./src/GeekToolsTest/bin/Debug/GeekToolsTest.dll
