language: csharp
solution: GeekTools.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore GeekTools.sln

script:
  - xbuild GeekTools.sln
  - nunit-console GeekToolsTest/bin/Release/GeekToolsTest.dll
